// Package pagination provides cursor-based pagination utilities. The cursor
// format is an opaque base64-encoded 8-byte big-endian Unix timestamp, which
// keeps URL-safe cursors small while supporting nanosecond-resolution ordering
// in the future via format versioning.
package pagination

import (
	"encoding/base64"
	"encoding/binary"
	"errors"
	"fmt"
	"time"
)

// ErrInvalidCursor is returned when a cursor string cannot be decoded.
var ErrInvalidCursor = errors.New("pagination: invalid cursor")

// EncodeCursor encodes a time.Time to an opaque, URL-safe base64 cursor string.
// Internally stores the Unix timestamp (int64) as 8 big-endian bytes.
func EncodeCursor(t time.Time) string {
	var b [8]byte                                      // stack-allocated; avoids heap allocation per call
	binary.BigEndian.PutUint64(b[:], uint64(t.Unix())) //nolint:gosec // safe: Unix() fits in int64, conversion intentional

	return base64.URLEncoding.EncodeToString(b[:])
}

// DecodeCursor decodes an opaque cursor string back to a time.Time.
// Accepts both URL-safe and standard base64 encodings for forward compatibility.
// Returns ErrInvalidCursor (wrapping the root cause) on any decode failure.
func DecodeCursor(s string) (time.Time, error) {
	b, err := base64.URLEncoding.DecodeString(s)
	if err != nil {
		// Accept standard base64 as a fallback (e.g., cursors generated by older clients)
		b, err = base64.StdEncoding.DecodeString(s)
		if err != nil {
			return time.Time{}, fmt.Errorf("%w: bad encoding: %w", ErrInvalidCursor, err)
		}
	}

	if len(b) < 8 {
		return time.Time{}, fmt.Errorf("%w: payload too short (%d bytes)", ErrInvalidCursor, len(b))
	}

	unix := int64(binary.BigEndian.Uint64(b[:8])) //nolint:gosec // safe: uint64 timestamp fits in int64 for any valid Unix time

	return time.Unix(unix, 0), nil
}

// ListMeta contains count metadata attached to list responses.
// Embed or include in list response structs to expose total result counts.
type ListMeta struct {
	Total int `json:"total"`
}

// CursorPagination contains cursor-based pagination metadata for feed-style
// endpoints where offset pagination is impractical. Consumers use Cursor to
// fetch the next page and HasMore to decide whether to request one.
type CursorPagination struct {
	Cursor  string `json:"cursor,omitempty"`
	HasMore bool   `json:"has_more"`
	Limit   int    `json:"limit"`
}
